# copy configuration_minicpm.py; downsample_mlp.py; 替换 image_processing_minicpmv.py; 复制modeling_minicpmv.py；modeling_navit_siglip.py；替换processing_minicpmv.py；复制resampler.py

cp /path/to/checkpoints/siglip_ours/separated_perceiver_ref/configuration_minicpm.py /path/to/checkpoints/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/v0-20260208-221828/checkpoint-1000/separated_models/perceiver/configuration_minicpm.py

cp /path/to/checkpoints/siglip_ours/separated_perceiver_ref/downsample_mlp.py /path/to/checkpoints/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/v0-20260208-221828/checkpoint-1000/separated_models/perceiver/downsample_mlp.py

cp /path/to/checkpoints/siglip_ours/separated_perceiver_ref/image_processing_minicpmv.py /path/to/checkpoints/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/v0-20260208-221828/checkpoint-1000/separated_models/perceiver/image_processing_minicpmv.py

cp /path/to/checkpoints/siglip_ours/separated_perceiver_ref/modeling_minicpmv.py /path/to/checkpoints/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/v0-20260208-221828/checkpoint-1000/separated_models/perceiver/modeling_minicpmv.py

cp /path/to/checkpoints/siglip_ours/separated_perceiver_ref/modeling_navit_siglip.py /path/to/checkpoints/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/v0-20260208-221828/checkpoint-1000/separated_models/perceiver/modeling_navit_siglip.py

cp /path/to/checkpoints/siglip_ours/separated_perceiver_ref/processing_minicpmv.py /path/to/checkpoints/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/v0-20260208-221828/checkpoint-1000/separated_models/perceiver/processing_minicpmv.py

cp /path/to/checkpoints/siglip_ours/separated_perceiver_ref/resampler.py /path/to/checkpoints/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/v0-20260208-221828/checkpoint-1000/separated_models/perceiver/resampler.py

cp /path/to/checkpoints/siglip_ours/separated_perceiver_ref/preprocessor_config.json /path/to/checkpoints/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/v0-20260208-221828/checkpoint-1000/separated_models/perceiver/preprocessor_config.json

# if perceiver need to skip layers

cp /path/to/checkpoints/siglip_ours/separated_perceiver_ref/modeling_minicpmv_with_skip.py /path/to/checkpoints/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/Ours_MiniCPM_V45_MLP_SFT_2node_zero3_reproduce_nopacking/v0-20260208-221828/checkpoint-1000/separated_models/perceiver/modeling_minicpmv.py
